import { LISTAS } from '../fixtures/src/listas.ts';
import type { WorkbookSpec } from './lib/workbook-writer.ts';

export const TEMPLATE_SPEC: WorkbookSpec = {
  listas: LISTAS,
  movimentos: [
    {
      data: '2026-02-05',
      doc: 'R-001',
      descricao: 'Inscrições (exemplo fictício)',
      atividade: 'Zumba na Caneca',
      rubrica: 'Inscrições e bilheteira',
      subRubrica: 'Bilheteira',
      tipo: 'Entrada',
      meio: 'Caixa',
      valorCents: 12000,
    },
    {
      data: '2026-02-06',
      doc: 'P-001',
      descricao: 'Cartazes e impressões (exemplo fictício)',
      atividade: 'Zumba na Caneca',
      rubrica: 'Comunicação e gráfica',
      subRubrica: 'Cartazes e impressões',
      tipo: 'Saída',
      meio: 'Caixa',
      valorCents: 4800,
    },
    {
      data: '2026-02-10',
      doc: 'P-002',
      descricao: 'Aluguer de som (exemplo fictício)',
      atividade: 'Zumba na Caneca',
      rubrica: 'Produção (som, luz, palco)',
      subRubrica: 'Som e luz',
      tipo: 'Saída',
      meio: 'Banco',
      valorCents: 30000,
    },
    {
      data: '2026-02-12',
      doc: 'R-002',
      descricao: 'Patrocínio do ginásio (exemplo fictício)',
      atividade: 'Zumba na Caneca',
      rubrica: 'Patrocínios',
      subRubrica: 'Patrocínio do evento',
      tipo: 'Entrada',
      meio: 'Banco',
      valorCents: 50000,
    },
    {
      data: '2026-02-15',
      doc: null,
      descricao: 'Vendas do bar por TPA (exemplo fictício)',
      atividade: 'Zumba na Caneca',
      rubrica: 'Bar e merchandising',
      subRubrica: 'Bar',
      tipo: 'Entrada',
      meio: 'TPA',
      valorCents: 8550,
    },
    {
      data: '2026-02-16',
      doc: 'P-003',
      descricao: 'Caução do alojamento (exemplo fictício)',
      atividade: '20º CITADÃO',
      rubrica: 'Alimentação e alojamento',
      subRubrica: 'Alojamento',
      tipo: 'Saída',
      meio: 'Banco',
      valorCents: 40000,
    },
    {
      data: '2026-02-20',
      doc: 'R-003',
      descricao: 'Devolução de parte da caução (exemplo de reembolso)',
      atividade: '20º CITADÃO',
      rubrica: 'Alimentação e alojamento',
      subRubrica: 'Alojamento',
      tipo: 'Entrada',
      meio: 'Banco',
      valorCents: 10000,
    },
    {
      data: '2026-02-22',
      doc: 'T-001',
      descricao: 'Depósito de numerário (saída da caixa)',
      atividade: 'Funcionamento',
      rubrica: 'Transferências internas',
      subRubrica: null,
      tipo: 'Saída',
      meio: 'Caixa',
      valorCents: 10000,
    },
    {
      data: '2026-02-22',
      doc: 'T-001',
      descricao: 'Depósito de numerário (entrada no banco)',
      atividade: 'Funcionamento',
      rubrica: 'Transferências internas',
      subRubrica: null,
      tipo: 'Entrada',
      meio: 'Banco',
      valorCents: 10000,
    },
  ],
  pendentes: [
    {
      tipo: 'A receber',
      entidade: 'Câmara Municipal (exemplo)',
      descricao: 'Apoio ao evento por receber',
      atividade: 'Zumba na Caneca',
      valorCents: 25000,
      dataRegisto: '2026-02-10',
      dataLiquidacao: null,
      notas: 'Protocolo assinado, pagamento previsto em março',
    },
    {
      tipo: 'A pagar',
      entidade: 'Gráfica Exemplo',
      descricao: 'Impressão de t-shirts',
      atividade: 'Festivais',
      valorCents: 18000,
      dataRegisto: '2026-02-20',
      dataLiquidacao: null,
      notas: null,
    },
  ],
  orcamento: [
    {
      ambito: 'Zumba na Caneca',
      tipo: 'Entrada',
      rubrica: 'Inscrições e bilheteira',
      subRubrica: 'Bilheteira',
      orcadoCents: 40000,
    },
    {
      ambito: 'Zumba na Caneca',
      tipo: 'Saída',
      rubrica: 'Produção (som, luz, palco)',
      subRubrica: 'Som e luz',
      orcadoCents: 30000,
    },
    {
      ambito: '2026',
      tipo: 'Saída',
      rubrica: 'Comunicação e gráfica',
      subRubrica: null,
      orcadoCents: 20000,
    },
  ],
  generos: [
    {
      data: '2026-02-14',
      atividade: 'Zumba na Caneca',
      tipo: 'Cedência de sala (exemplo)',
      quantidade: '1 dia',
      emFalta: null,
      valorEstimadoCents: 15000,
    },
    {
      data: null,
      atividade: 'Festivais',
      tipo: 'Cartazes oferecidos (exemplo)',
      quantidade: '20 unidades',
      emFalta: 5,
      valorEstimadoCents: null,
    },
  ],
  saldos: [
    {
      data: '2026-01-31',
      conta: 'Caixa',
      saldoCents: 15000,
      fonte: 'Contagem',
    },
    {
      data: '2026-01-31',
      conta: 'Banco',
      saldoCents: 300000,
      fonte: 'Extrato',
    },
    {
      data: '2026-02-28',
      conta: 'Caixa',
      saldoCents: 12200,
      fonte: 'Contagem',
    },
    {
      data: '2026-02-28',
      conta: 'Banco',
      saldoCents: 308550,
      fonte: 'Extrato',
    },
  ],
  instrucoes: [
    {
      titulo: 'Modelo de tesouraria do TUNADÃO 1998',
      paragrafos: [
        'Este ficheiro reúne os dados da tesouraria. Depois de preenchido, carregue-o na página do gerador de relatórios para obter o relatório em PDF.',
        'Todas as linhas de exemplo são fictícias. Apague-as antes de começar a registar os seus movimentos.',
      ],
    },
    {
      titulo: 'Para que serve cada separador',
      paragrafos: [
        'Movimentos: cada recebimento e cada pagamento, com a data em que o dinheiro entrou ou saiu. A tuna trabalha em regime de caixa, por isso só contam os movimentos de dinheiro.',
        'Pendentes: valores a receber e dívidas a pagar que ainda não foram liquidados. Preencha a data de liquidação quando o dinheiro mudar de mãos e registe então o movimento correspondente.',
        'Orçamento: o valor orçado por rubrica, para uma atividade ou para um período (por exemplo, "20º CITADÃO" ou "2026").',
        'Géneros: apoios em espécie. São listados à parte e nunca entram no saldo.',
        'Saldos: pontos de controlo do dinheiro que existe em cada conta. Ver a secção seguinte.',
        'Listas: as rubricas, sub-rubricas, atividades e meios de pagamento que aparecem nas listas suspensas dos outros separadores.',
      ],
    },
    {
      titulo: 'Como funcionam os pontos de controlo (Saldos)',
      paragrafos: [
        'Cada linha indica o saldo de uma conta (Caixa ou Banco) no fim de um dia, depois de contar todos os movimentos desse dia: é o saldo contabilístico, não o saldo disponível.',
        'A primeira linha de cada conta é o saldo de abertura. Não registe saldos iniciais como movimentos.',
        'A fonte indica de onde vem o valor: Extrato (extrato bancário), Contagem (contagem física da caixa) ou Declarado (indicado sem comprovativo).',
        'Cada novo ponto de controlo é conferido com o anterior: o saldo anterior mais os movimentos entre as duas datas tem de dar o novo saldo. Se não der, o gerador indica a diferença.',
      ],
    },
    {
      titulo: 'Reembolsos e transferências',
      paragrafos: [
        'Reembolso: se recebeu de volta dinheiro de uma despesa (por exemplo, uma caução), registe uma Entrada com a rubrica dessa despesa. O valor abate à despesa e não conta como receita.',
        'Transferência entre contas (por exemplo, depositar numerário no banco): registe duas linhas com a rubrica "Transferências internas", uma Saída na conta de origem e uma Entrada na conta de destino, com o mesmo valor e a mesma data. Não contam como receita nem despesa.',
      ],
    },
    {
      titulo: 'Regras de preenchimento',
      paragrafos: [
        'O valor é sempre positivo. O sentido do movimento indica-se na coluna Tipo (Entrada ou Saída).',
        'A sub-rubrica é opcional. Quando a deixa vazia, o movimento fica na própria rubrica.',
        'Escolha rubricas, sub-rubricas, atividades e meios nas listas suspensas. A lista da sub-rubrica mostra todas as sub-rubricas; escolha uma que pertença à rubrica indicada.',
        'Nunca edite as colunas Conta, Valor com sinal (€) e Conta para o resultado: são calculadas automaticamente a partir das restantes.',
        'Para acrescentar uma rubrica, atividade ou meio, escreva-o no fim da respetiva coluna do separador Listas. As listas suspensas passam a incluí-lo.',
      ],
    },
  ],
};
